`timescale 1ns/1ps
`default_nettype none
`include "mul_ugemm_regen/vec/mul_ugemm_regen_params.vh"

// Self-checking co-simulation testbench for the unipolar and bipolar
// mul_ugemm_regen variants. Vectors are generated by the Python model.

module mul_ugemm_regen_tb;
    reg i_clk;
    reg i_rst_n;
    reg in_0_u, in_1_u, in_0_b, in_1_b;
    wire out_u, out_b;

    mul_ugemm_regen_unipolar #(.WIDTH(`GEN_WIDTH)) dut_u (
        .i_clk(i_clk), .i_rst_n(i_rst_n),
        .i_input_0(in_0_u), .i_input_1(in_1_u), .o_output(out_u)
    );
    mul_ugemm_regen_bipolar #(.WIDTH(`GEN_WIDTH)) dut_b (
        .i_clk(i_clk), .i_rst_n(i_rst_n),
        .i_input_0(in_0_b), .i_input_1(in_1_b), .o_output(out_b)
    );

    // LINE_BYTES sizes the line buffer, which holds LINE_BYTES bytes, so a
    // newline-terminated row carries at most LINE_BYTES-1 payload bytes, and
    // DATA_COLS is the column count every data row carries. Neither constant
    // can be set wrong and still let a malformed row through, because the
    // trailing sentinel makes the column check two-sided. A DATA_COLS set too
    // large fatals on the first clean row. A LINE_BYTES set too large costs
    // guard precision rather than correctness, because the length assertion
    // can then fire only at the buffer boundary instead of near the true row
    // width, so both constants are measured from the vec file rather than
    // guessed.
    localparam LINE_BYTES = 32;
    localparam DATA_COLS  = 7;

    integer fd, code, chars, n, fails;
    reg rst, in_0_u_s, in_1_u_s, in_0_b_s, in_1_b_s, exp_u, exp_b;
    reg [8*8-1:0] extra;
    reg [8*8-1:0] tok_rst;
    reg [8*8-1:0] tok_in_0_u_s;
    reg [8*8-1:0] tok_in_1_u_s;
    reg [8*8-1:0] tok_exp_u;
    reg [8*8-1:0] tok_in_0_b_s;
    reg [8*8-1:0] tok_in_1_b_s;
    reg [8*8-1:0] tok_exp_b;
    reg [8*LINE_BYTES-1:0] line;

    initial i_clk = 1'b0;
    always #5 i_clk = ~i_clk;


    task reset_dut;
        begin
            i_rst_n = 1'b0;
            @(posedge i_clk);
            @(negedge i_clk);
            i_rst_n = 1'b1;
        end
    endtask


    initial begin
        i_rst_n = 1'b1;
        in_0_u = 1'b0;
        in_1_u = 1'b0;
        in_0_b = 1'b0;
        in_1_b = 1'b0;
        n = 0;
        fails = 0;

        // Each row is compared before the posedge, so this testbench can only drive a
        // pp_delay of 0; that pre-posedge sampling is what enforces it. This check
        // rejects a model whose pp_delay stopped agreeing with that assumption.
        if (`GEN_PP_DELAY != 0) begin
            $display("FAIL mul_ugemm_regen: testbench samples combinationally, model pp_delay is %0d", `GEN_PP_DELAY);
            $finish;
        end
        reset_dut;

        fd = $fopen("vec/mul_ugemm_regen.vec", "r");
        if (fd == 0) begin
            $display("ERROR: cannot open vec/mul_ugemm_regen.vec");
            $finish;
        end

        // A row carrying any other column count, a row that fills the line
        // buffer, or an x or z data field ends the run with a fatal at that row,
        // so a row can never borrow a column from its neighbour. A blank line is
        // benign only at end of file.
        chars = 1;
        while (chars != 0) begin
            chars = $fgets(line, fd);
            if (chars != 0) begin
                if (chars == LINE_BYTES && line[7:0] !== "\n")
                    $fatal(1, "mul_ugemm_regen: row %0d fills the %0d byte line buffer", n + 1, LINE_BYTES);
                // The field count of this format string must match DATA_COLS.
                code = $sscanf(line, "%s %s %s %s %s %s %s %s",
                               tok_rst, tok_in_0_u_s, tok_in_1_u_s, tok_exp_u, tok_in_0_b_s, tok_in_1_b_s, tok_exp_b, extra);
                if (code == 0) begin
                    // A blank line is benign only at end of file.
                    if ($fgets(line, fd) == 0)
                        chars = 0;
                    else
                        $fatal(1, "mul_ugemm_regen: row %0d is blank", n + 1);
                end else begin
                    if (code != DATA_COLS)
                        $fatal(1, "mul_ugemm_regen: row %0d scanned %0d columns, expected %0d", n + 1, code, DATA_COLS);
                    // Input columns: a token wider than one bit is a corrupt vec file,
                    // so it is rejected here rather than truncated into stimulus.
                    if (tok_rst !== "0" && tok_rst !== "1")
                        $fatal(1, "mul_ugemm_regen: row %0d input field rst is \"%0s\", expected a single 0 or 1", n + 1, tok_rst);
                    rst = (tok_rst == "1");
                    if (tok_in_0_u_s !== "0" && tok_in_0_u_s !== "1")
                        $fatal(1, "mul_ugemm_regen: row %0d input field in_0_u is \"%0s\", expected a single 0 or 1", n + 1, tok_in_0_u_s);
                    in_0_u_s = (tok_in_0_u_s == "1");
                    if (tok_in_1_u_s !== "0" && tok_in_1_u_s !== "1")
                        $fatal(1, "mul_ugemm_regen: row %0d input field in_1_u is \"%0s\", expected a single 0 or 1", n + 1, tok_in_1_u_s);
                    in_1_u_s = (tok_in_1_u_s == "1");
                    if (tok_in_0_b_s !== "0" && tok_in_0_b_s !== "1")
                        $fatal(1, "mul_ugemm_regen: row %0d input field in_0_b is \"%0s\", expected a single 0 or 1", n + 1, tok_in_0_b_s);
                    in_0_b_s = (tok_in_0_b_s == "1");
                    if (tok_in_1_b_s !== "0" && tok_in_1_b_s !== "1")
                        $fatal(1, "mul_ugemm_regen: row %0d input field in_1_b is \"%0s\", expected a single 0 or 1", n + 1, tok_in_1_b_s);
                    in_1_b_s = (tok_in_1_b_s == "1");
                    // Expected-output columns: a token wider than one bit would be
                    // truncated into a bit that can match the DUT, so a wrong answer
                    // would be accepted. Compare the column as characters instead.
                    if (tok_exp_u !== "0" && tok_exp_u !== "1")
                        $fatal(1, "mul_ugemm_regen: row %0d expected field exp_u is \"%0s\", expected a single 0 or 1", n + 1, tok_exp_u);
                    exp_u = (tok_exp_u == "1");
                    if (tok_exp_b !== "0" && tok_exp_b !== "1")
                        $fatal(1, "mul_ugemm_regen: row %0d expected field exp_b is \"%0s\", expected a single 0 or 1", n + 1, tok_exp_b);
                    exp_b = (tok_exp_b == "1");
                    in_0_u = in_0_u_s;
                    in_1_u = in_1_u_s;
                    in_0_b = in_0_b_s;
                    in_1_b = in_1_b_s;
                    if (rst)
                        reset_dut;
                    #1;
                    n = n + 1;
                    if (out_u !== exp_u) begin
                        $display("FAIL uni cycle=%0d got=%b exp=%b", n, out_u, exp_u);
                        fails = fails + 1;
                    end
                    if (out_b !== exp_b) begin
                        $display("FAIL bi cycle=%0d got=%b exp=%b", n, out_b, exp_b);
                        fails = fails + 1;
                    end
                    @(posedge i_clk);
                    @(negedge i_clk);
                end
            end
        end
        $fclose(fd);

        // Every generated row must have been compared, so a vec file that lost
        // rows fails instead of passing on the rows it kept.
        if (n != `GEN_VECTORS) begin
            $display("FAIL mul_ugemm_regen: compared %0d vectors, generator wrote %0d",
                     n, `GEN_VECTORS);
            fails = fails + 1;
        end

        if (fails == 0)
            $display("PASS mul_ugemm_regen: %0d/%0d vectors", n, n);
        else
            $display("FAIL mul_ugemm_regen: %0d mismatch(es) over %0d vectors", fails, n);
        $finish;
    end
endmodule
`default_nettype wire
