name: napl
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.9
  - pip
  - pyyaml
  - yamlordereddictloader
  - loguru
  - pyfiglet
  - pip:
    - torch>=2.14
    - pylfsr
    - pytest
    - numpy
    - scipy
    - matplotlib
