# Global configuration for NAPL
global_config:

    # spike data type for simulation
    spike_type: 'torch.int8'
    
    # non-spike data type for simulation
    # for both number sequence and accumulation buffer
    non_spike_type: 'torch.float32'
