`timescale 1ns/1ps
`default_nettype none
`include "mul_shiftreg/vec/mul_shiftreg_params.vh"

// Self-checking co-simulation testbench for the unipolar and bipolar
// mul_shiftreg variants. Vectors are generated by the Python model.

module mul_shiftreg_tb;
    reg i_clk;
    reg i_rst_n;
    reg in_0_u, in_1_u, in_0_b, in_1_b;
    wire out_u, out_b;

    mul_shiftreg_unipolar #(.WIDTH(`GEN_WIDTH)) dut_u (
        .i_clk(i_clk), .i_rst_n(i_rst_n),
        .i_input_0(in_0_u), .i_input_1(in_1_u), .o_out(out_u)
    );
    mul_shiftreg_bipolar #(.WIDTH(`GEN_WIDTH)) dut_b (
        .i_clk(i_clk), .i_rst_n(i_rst_n),
        .i_input_0(in_0_b), .i_input_1(in_1_b), .o_out(out_b)
    );

    integer fd, code, n, fails;
    reg rst, exp_u, exp_b;

    initial i_clk = 1'b0;
    always #5 i_clk = ~i_clk;


    task reset_dut;
        begin
            i_rst_n = 1'b0;
            @(posedge i_clk);
            @(negedge i_clk);
            i_rst_n = 1'b1;
        end
    endtask


    initial begin
        i_rst_n = 1'b1;
        in_0_u = 1'b0;
        in_1_u = 1'b0;
        in_0_b = 1'b0;
        in_1_b = 1'b0;
        n = 0;
        fails = 0;

        if (`GEN_PP_DELAY != 0) begin
            $display("FAIL mul_shiftreg: expected pp_delay 0");
            $finish;
        end
        reset_dut;

        fd = $fopen("vec/mul_shiftreg.vec", "r");
        if (fd == 0) begin
            $display("ERROR: cannot open vec/mul_shiftreg.vec");
            $finish;
        end

        while (!$feof(fd)) begin
            code = $fscanf(
                fd, "%b %b %b %b %b %b %b\n",
                rst, in_0_u, in_1_u, exp_u, in_0_b, in_1_b, exp_b
            );
            if (code == 7) begin
                if (rst)
                    reset_dut;
                #1;
                n = n + 1;
                if (out_u !== exp_u) begin
                    $display("FAIL uni cycle=%0d got=%b exp=%b", n, out_u, exp_u);
                    fails = fails + 1;
                end
                if (out_b !== exp_b) begin
                    $display("FAIL bi cycle=%0d got=%b exp=%b", n, out_b, exp_b);
                    fails = fails + 1;
                end
                @(posedge i_clk);
                @(negedge i_clk);
            end
        end
        $fclose(fd);

        if (fails == 0)
            $display("PASS mul_shiftreg: %0d/%0d vectors", n, n);
        else
            $display("FAIL mul_shiftreg: %0d mismatch(es) over %0d vectors", fails, n);
        $finish;
    end
endmodule
`default_nettype wire
