import torch

from napl.sim.base import napl_base, hw_params
from napl.sim.operation import bi2uni, div_cordiv


class sqrt_traceiscb(napl_base):
    r"""
    Approximate square root with traced bit insertion and correlated division.

    Use this streaming kernel for unipolar or bipolar rate-coded square root
    when the trace should be generated by an in-stream correlation-based divider.

    The precise target rate-domain operation is

    .. math::

       y = \sqrt{x}.

    Let q_t be the saved trace, d_t the delayed-input bit, and x_t the current
    input spike. The correlated-divider trace update is

    .. math::

       \begin{aligned}
       u_t &= q_t \mathbin{\lor} x_t, &
       \hat u_t &= \begin{cases}u_t & (\text{unipolar}),\\
       B(u_t) & (\text{bipolar}),\end{cases}\\
       v_t &= (1-d_t)\mathbin{\land}\hat u_t, &
       w_t &= d_t\mathbin{\lor}v_t,\\
       q_{t+1} &= C(v_t,w_t), &
       d_{t+1} &= 1-d_t,\\
       p_q &= \frac{p_{\hat u}}{p_{\hat u}+1}, &
       p_{\hat u}^2 &= p_x.
       \end{aligned}

    Here B is bi2uni and C is div_cordiv; the piecewise line selects B only
    for bipolar input.

    .. rubric:: Example

    .. code-block:: python

        import torch
        from napl import sqrt_traceiscb

        operation = sqrt_traceiscb({'polarity': 'unipolar'})
        output = operation(torch.tensor([0.0, 1.0]))

    .. container:: api-references

        .. rubric:: References

        *In-Stream Stochastic Division and Square Root via Correlation*, DAC, 2019.

        *In-Stream Correlation-Based Division and Bit-Inserting Square Root in Stochastic Computing*, IEEE Design and Test, 2021.
    """


    def __init__(
        self,
        config={
            'polarity' : 'bipolar',
        },
    ):
        """
        Configure the input encoding and fixed correlated-divider trace path.

        .. container:: api-parameter-list

            **Parameters:**

            - **config** – Configuration mapping.

              - **polarity**: Stream encoding, either ``"unipolar"`` or ``"bipolar"``; the default is ``"bipolar"``.
              - **name**: Optional module name.
        """
        super().__init__(config, ['polarity'], polarity_required=True)

        #: Correlated-divider stage that updates the square-root trace.
        self.cordiv_kernel = div_cordiv({'depth': 2, 'generator': 'sobol'})
        #: One-timestep delayed input used by the trace update.
        self.dff: torch.Tensor
        self.register_buffer('dff', torch.zeros(1, dtype=torch.int8))
        #: Saved square-root trace inserted into the current input stream.
        self.trace: torch.Tensor
        self.register_buffer('trace', torch.zeros(1, dtype=torch.int8))

        if self.polarity == 'bipolar':
            #: Converter that supplies a unipolar magnitude stream in bipolar mode.
            self.bi2uni = bi2uni({'width': 3})
        #: Hardware latency and timing metadata for the composed square-root path.
        self.hw = hw_params(pp_delay=0)

        self.encoding_io = {'input': 'rc', 'output': 'rc'}
        self.polarity_io = {'input': self.polarity, 'output': self.polarity}
        self.correlation_i = {}
        self.stability_flux = 1.0


    def _reset(self):
        """
        Clear the local delay and trace buffers.

        Registered child kernels are reset by :meth:`reset` before this local reset.
        """
        self.dff.resize_(1).zero_()
        self.trace.resize_(1).zero_()


    def forward(self, input):
        """
        Process one timestep of a rate-coded input stream.

        The call inserts the saved trace into the current input and then updates
        the trace through the correlated-divider path.

        Args:
            input: Tensor of current 0/1 spikes in the configured polarity.

        Returns:
            0/1 square-root output spike tensor with the same shape as ``input``.

        **Example:**

        .. code-block:: python

            output = operation(torch.tensor([0.0, 1.0]))
        """
        trace = self.trace
        # For 0/1 values, ((1 - trace) & input) + trace == trace | input.
        output = (trace | input.type(torch.int8)).type(self.stype)
        if self.polarity == 'unipolar':
            # P_trace = P_out / (P_out + 1).
            self._unipolar_trace(output)
        else:
            # P_trace = (2 * P_out - 1) / ((2 * P_out - 1) + 1).
            out = self.bi2uni(output)
            self._unipolar_trace(out)
        return output


    def _unipolar_trace(self, output):
        """Update the saved trace from a unipolar output spike."""
        dff_inv = 1 - self.dff
        dividend = dff_inv & output.type(torch.int8)
        divisor = self.dff | dividend

        trace = self.cordiv_kernel(dividend, divisor)
        if self.trace.shape == trace.shape:
            self.trace.copy_(trace.detach())
        else:
            self.trace.resize_as_(trace).copy_(trace.detach())

        if self.dff.shape == dff_inv.shape:
            self.dff.copy_(dff_inv.detach())
        else:
            self.dff.resize_as_(dff_inv).copy_(dff_inv.detach())
