import torch

from napl.sim.base import napl_base, hw_params
from napl.sim.operation import bi2uni, div_cordiv


class sqrt_traceiscb(napl_base):
    """
    Approximate square root with traced bit insertion and correlated division.

    Use this streaming kernel for unipolar or bipolar rate-coded square root
    when the trace should be generated by an in-stream correlation-based divider.

    .. rubric:: Example

    .. code-block:: python

        import torch
        from napl import sqrt_traceiscb

        operation = sqrt_traceiscb({'polarity': 'unipolar'})
        output = operation(torch.tensor([0.0, 1.0]))

    .. container:: api-references

        .. rubric:: References

        *In-Stream Stochastic Division and Square Root via Correlation*.

        *In-Stream Correlation-Based Division and Bit-Inserting Square Root in Stochastic Computing*.
    """


    def __init__(
        self,
        config={
            'polarity' : 'bipolar',
        },
    ):
        """
        Configure the input encoding and fixed correlated-divider trace path.

        .. container:: api-parameter-list

            **Parameters:**

            - **config** – Configuration mapping.

              - **polarity**: Stream encoding, either ``"unipolar"`` or ``"bipolar"``; the default is ``"bipolar"``.
              - **name**: Optional module name.
        """
        super().__init__(config, ['polarity'], polarity_required=True)
        #: Hardware latency and timing metadata for the composed square-root path.
        self.hw = hw_params(pp_delay=0)

        #: Correlated-divider stage that updates the square-root trace.
        self.cordiv_kernel = div_cordiv({'depth': 2, 'generator': 'sobol'})
        #: One-timestep delayed input used by the trace update.
        self.dff: torch.Tensor
        self.register_buffer('dff', torch.zeros(1, dtype=torch.int8))
        #: Saved square-root trace inserted into the current input stream.
        self.trace: torch.Tensor
        self.register_buffer('trace', torch.zeros(1, dtype=torch.int8))

        if self.polarity == 'bipolar':
            #: Converter that supplies a unipolar magnitude stream in bipolar mode.
            self.bi2uni = bi2uni({'width': 3})


    def _reset(self):
        """
        Clear the local delay and trace buffers.

        Registered child kernels are reset by :meth:`reset` before this local reset.
        """
        self.dff.resize_(1).zero_()
        self.trace.resize_(1).zero_()


    def forward(self, input):
        """
        Process one timestep of a rate-coded input stream.

        The call inserts the saved trace into the current input and then updates
        the trace through the correlated-divider path.

        Args:
            input: Tensor of current 0/1 spikes in the configured polarity.

        Returns:
            0/1 square-root output spike tensor with the same shape as ``input``.

        **Example:**

        .. code-block:: python

            output = operation(torch.tensor([0.0, 1.0]))
        """
        trace = self.trace
        # For 0/1 values, ((1 - trace) & input) + trace == trace | input.
        output = (trace | input.type(torch.int8)).type(self.stype)
        if self.polarity == 'unipolar':
            # P_trace = P_out / (P_out + 1).
            self.unipolar_trace(output)
        else:
            # P_trace = (2 * P_out - 1) / ((2 * P_out - 1) + 1).
            out = self.bi2uni(output)
            self.unipolar_trace(out)
        return output


    def unipolar_trace(self, output):
        """
        Update the saved trace from a unipolar output spike.

        This method advances the correlated-divider child, writes the trace
        buffer, and toggles the local delay bit.

        Args:
            output: Tensor of current 0/1 unipolar output spikes.

        Returns:
            ``None``.

        **Example:**

        .. code-block:: python

            operation.unipolar_trace(torch.tensor([0.0, 1.0]))
        """
        dff_inv = 1 - self.dff
        dividend = dff_inv & output.type(torch.int8)
        divisor = self.dff | dividend

        trace = self.cordiv_kernel(dividend, divisor)
        if self.trace.shape == trace.shape:
            self.trace.copy_(trace.detach())
        else:
            self.trace.resize_as_(trace).copy_(trace.detach())

        if self.dff.shape == dff_inv.shape:
            self.dff.copy_(dff_inv.detach())
        else:
            self.dff.resize_as_(dff_inv).copy_(dff_inv.detach())
