"""Sweep every profile_<name>.py in this directory and write flux_stability.yaml."""

import glob
import importlib
import os
import sys
import time
from importlib.resources import files

import yaml

import napl.sim.module as napl_module
import napl.sim.operation as napl_operation

# This directory holds the shared runner and the per-name profile modules.
_HERE = os.path.dirname(os.path.abspath(__file__))

# Fields copied verbatim from each result dict into the yaml (some are optional).
_META_KEYS = ('timesteps', 'shape', 'seed', 'n_inputs', 'n_outputs', 'model')

# Per-layer taxonomy source: layer name -> (package, yaml file, membership module).
_TAXONOMIES = (
    ('operation', 'napl.sim.operation', 'operation_type_mapping.yaml', napl_operation),
    ('module', 'napl.sim.module', 'module_type_mapping.yaml', napl_module),
)


def load_taxonomies():
    """Return name -> (layer, group) merged from both taxonomies, resolved via package location."""
    name_map = {}
    for layer, package, filename, _member in _TAXONOMIES:
        groups = yaml.safe_load(files(package).joinpath(filename).read_text())
        for group, names in groups.items():
            for name in names:
                name_map[name] = (layer, group)
    return name_map


def load_layer_names():
    """Return layer -> set of taxonomy names, for per-layer validation."""
    per_layer = {}
    for layer, package, filename, _member in _TAXONOMIES:
        groups = yaml.safe_load(files(package).joinpath(filename).read_text())
        per_layer[layer] = {name for names in groups.values() for name in names}
    return per_layer


def discover_names():
    """Return sorted names from sibling profile_<name>.py files, minus the runner and self."""
    skip = {'profile_common.py', os.path.basename(__file__)}
    names = []
    for path in glob.glob(os.path.join(_HERE, 'profile_*.py')):
        base = os.path.basename(path)
        if base in skip:
            continue
        names.append(base[len('profile_'):-len('.py')])
    return sorted(names)


def validate(name_map, discovered):
    """Raise if a discovered name is in neither or both taxonomies, or if a taxonomy entry lacks a profile file or is not a package member."""
    per_layer = load_layer_names()
    # Each discovered profile file must belong to exactly one taxonomy.
    for name in discovered:
        hits = [layer for layer, names in per_layer.items() if name in names]
        if len(hits) != 1:
            where = 'neither taxonomy' if not hits else 'both taxonomies (' + ', '.join(hits) + ')'
            raise ValueError(f'profile_{name}.py is in {where}; it must appear in exactly one')
    # Each taxonomy entry must have a profile file and be a member of its package.
    discovered_set = set(discovered)
    for layer, _package, filename, member in _TAXONOMIES:
        unknown = sorted(
            name for name in per_layer[layer]
            if name not in discovered_set or not hasattr(member, name))
        if unknown:
            raise ValueError(
                f'{filename} lists names that do not exist '
                f'(no profile_<name>.py or not a napl.sim.{layer} member): ' + ', '.join(unknown))


def sweep():
    """Profile every name, printing per-polarity progress, and return (results, failures)."""
    if _HERE not in sys.path:
        sys.path.insert(0, _HERE)
    results, failures = {}, {}
    for name in discover_names():
        try:
            module = importlib.import_module('profile_' + name)
            entries = module.profile()
            results[name] = entries
            fluxes = ', '.join(
                f'{e["polarity"]}={e["flux_stability"]}' for e in entries)
            print(f'{name} -> {fluxes}')
        except Exception as exc:
            failures[name] = repr(exc)
            print(f'{name} -> FAILED: {exc!r}')
    return results, failures


def to_yaml_fields(result):
    """Build one polarity's fields: rounded flux_stability plus present metadata, without 'polarity'."""
    fields = {'flux_stability': round(float(result['flux_stability']), 6)}
    for key in _META_KEYS:
        if key in result:
            fields[key] = result[key]
    return fields


_PACKAGE_HEADER = (
    '# Flux-stability values generated by zoo/profiling/flux_stability/sweep_profiling.py.\n'
    '# Regenerate: cd zoo/profiling/flux_stability && conda run -n napl python sweep_profiling.py\n'
)


def write_package_files(doc):
    """Write a flat class -> polarity -> flux_stability file into each layer's package dir."""
    for layer, _package, _filename, member in _TAXONOMIES:
        flat = {}
        for names in doc.get(layer, {}).values():
            for name, polarities in names.items():
                flat[name] = {pol: fields['flux_stability'] for pol, fields in polarities.items()}
        path = os.path.join(os.path.dirname(member.__file__), 'flux_stability.yaml')
        with open(path, 'w') as handle:
            handle.write(_PACKAGE_HEADER)
            yaml.safe_dump(flat, handle, sort_keys=True, default_flow_style=False)


def main():
    """Run the full sweep, write flux_stability.yaml, and print a summary line."""
    name_map = load_taxonomies()
    discovered = discover_names()
    validate(name_map, discovered)

    start = time.perf_counter()
    results, failures = sweep()
    elapsed = time.perf_counter() - start

    # Nest each polarity's fields under layer -> group -> name -> polarity.
    doc, per_layer_count = {}, {'operation': 0, 'module': 0}
    for name, entries in results.items():
        layer, group = name_map[name]
        for result in entries:
            doc.setdefault(layer, {}).setdefault(group, {}).setdefault(name, {})[result['polarity']] = \
                to_yaml_fields(result)
            per_layer_count[layer] += 1
    out_path = os.path.join(_HERE, 'flux_stability.yaml')
    with open(out_path, 'w') as handle:
        yaml.safe_dump(doc, handle, sort_keys=True, default_flow_style=False)

    # Emit the flat per-layer package files the base-ctor fill reads.
    write_package_files(doc)

    entry_count = sum(per_layer_count.values())
    if failures:
        print('Failed names: ' + ', '.join(f'{name} ({err})' for name, err in failures.items()))
    print(f'Sweep done: {len(results)} succeeded / {len(failures)} failed, '
          f'{entry_count} (name,polarity) entries written '
          f'(operation {per_layer_count["operation"]}, module {per_layer_count["module"]}) in {elapsed:.2f}s')


if __name__ == '__main__':
    main()
