"""Sweep flux-stability profiles across designed input stability levels."""

import argparse
import glob
import importlib
import os
import sys
import time
from importlib.resources import files

import yaml

import napl.sim.module as napl_module
import napl.sim.operation as napl_operation

import profile_common

# This directory holds the shared runner and the per-name profile modules.
_HERE = os.path.dirname(os.path.abspath(__file__))

# Fields copied verbatim from each result dict into the yaml (some are optional).
_META_KEYS = ('timesteps', 'shape', 'seed', 'n_inputs', 'n_outputs', 'model')

# Per-layer taxonomy source: layer name -> (package, yaml file, membership module).
_TAXONOMIES = (
    ('operation', 'napl.sim.operation', 'operation_type_mapping.yaml', napl_operation),
    ('module', 'napl.sim.module', 'module_type_mapping.yaml', napl_module),
)
_LAYERS = tuple(layer for layer, _package, _filename, _member in _TAXONOMIES)

# Normalized input-stability levels swept, one full profiling pass each.
_LEVELS = tuple(round(0.1 * step, 1) for step in range(1, 11))

_PACKAGE_HEADER = (
    '# Profiling results generated by zoo/profiling/flux_stability/sweep_stability.py.\n'
    '# Regenerate all layers: cd zoo/profiling/flux_stability && conda run -n napl python sweep_stability.py\n'
    '# Regenerate one layer: cd zoo/profiling/flux_stability && conda run -n napl python sweep_stability.py operation  (or module)\n'
)


def select_layers(selector=None):
    """Return the selected profiling layers, defaulting to both layers."""
    if selector is None:
        return _LAYERS
    if selector not in _LAYERS:
        raise ValueError(f'unknown layer {selector!r}; choose operation or module')
    return (selector,)


def selected_taxonomies(selector=None):
    """Return taxonomy records for the selected profiling layers."""
    layers = select_layers(selector)
    return tuple(record for record in _TAXONOMIES if record[0] in layers)


def load_taxonomies(selector=None):
    """Return name -> (layer, group) for the selected profiling layers."""
    name_map = {}
    for layer, package, filename, _member in selected_taxonomies(selector):
        groups = yaml.safe_load(files(package).joinpath(filename).read_text())
        for group, names in groups.items():
            for name in names:
                name_map[name] = (layer, group)
    return name_map


def load_layer_names(selector=None):
    """Return selected layer -> set of taxonomy names for validation."""
    per_layer = {}
    for layer, package, filename, _member in selected_taxonomies(selector):
        groups = yaml.safe_load(files(package).joinpath(filename).read_text())
        per_layer[layer] = {name for names in groups.values() for name in names}
    return per_layer


def discover_names(selector=None):
    """Return selected layer -> sorted names from its profile directory."""
    return {
        layer: sorted(
            os.path.basename(path)[len('profile_'):-len('.py')]
            for path in glob.glob(os.path.join(_HERE, layer, 'profile_*.py'))
        )
        for layer in select_layers(selector)
    }


def validate(name_map, discovered, selector=None):
    """Validate selected profiles against their layer taxonomy and package members."""
    discovered_layers = {}
    for layer in select_layers(selector):
        for name in discovered[layer]:
            previous_layer = discovered_layers.setdefault(name, layer)
            if previous_layer != layer:
                raise ValueError(
                    f'profile_{name}.py is in both {previous_layer} and {layer}; '
                    'it must appear in exactly one selected layer')
    per_layer = load_layer_names(selector)
    for layer, _package, filename, member in selected_taxonomies(selector):
        names = discovered[layer]
        unknown = sorted(name for name in names if name not in per_layer[layer])
        if unknown:
            raise ValueError(
                f'{layer}/profile_<name>.py has names not listed in {filename}: ' +
                ', '.join(unknown))
        discovered_set = set(names)
        unknown = sorted(
            name for name in per_layer[layer]
            if name not in discovered_set or name not in name_map or not hasattr(member, name))
        if unknown:
            raise ValueError(
                f'{filename} lists names that do not exist '
                f'(no {layer}/profile_<name>.py or not a napl.sim.{layer} member): ' +
                ', '.join(unknown))


def sweep(selector=None, discovered=None):
    """Profile selected names, printing progress, and return (results, name -> exception)."""
    layers = select_layers(selector)
    if discovered is None:
        discovered = discover_names(selector)
    if _HERE not in sys.path:
        sys.path.insert(0, _HERE)
    for layer in layers:
        layer_path = os.path.join(_HERE, layer)
        if layer_path not in sys.path:
            sys.path.insert(0, layer_path)
    results, failures = {}, {}
    names = sorted(name for layer in layers for name in discovered[layer])
    for name in names:
        try:
            module = importlib.import_module('profile_' + name)
            entries = module.profile()
            results[name] = entries
            fluxes = ', '.join(
                f'{e["polarity"]}={e["flux_stability"]}' for e in entries)
            print(f'{name} -> {fluxes}')
        except Exception as exc:
            failures[name] = exc
            print(f'{name} -> FAILED: {exc!r}')
    return results, failures


def to_yaml_fields(result):
    """Build one polarity's rounded profiling fields plus present metadata."""
    fields = {
        'flux_stability': round(float(result['flux_stability']), 6),
        'rmse': round(float(result['rmse']), 6),
    }
    for key in _META_KEYS:
        if key in result:
            fields[key] = result[key]
    return fields


def sweep_plain(selector=None, discovered=None):
    """Return (results, failures) of one pass with plain encoders, no designed stability."""
    profile_common.INPUT_NORMSTABILITY = None
    start = time.perf_counter()
    results, failures = sweep(selector, discovered)
    print(f'input_stab=plain: {len(results)} succeeded / {len(failures)} failed '
          f'in {time.perf_counter() - start:.2f}s')
    return results, failures


def _append_entry(polarities, result):
    """Append one profiled run's rounded fields to that polarity's parallel lists."""
    fields = to_yaml_fields(result)
    entry = {
        'flux_stability': fields['flux_stability'],
        'input_stability': round(float(result['input_stability']), 6),
        'rmse': fields['rmse'],
    }
    curves = polarities.setdefault(result['polarity'], {key: [] for key in entry})
    for key, value in entry.items():
        curves[key].append(value)


def is_temporal(name, per_level_failures):
    """Return whether every swept level rejected this class's generator as not rate coded."""
    return bool(per_level_failures) and all(
        isinstance(failures.get(name), profile_common.NotRateCoded)
        for failures in per_level_failures.values())


def _is_curve(entry):
    """Return whether a stored class entry is in the parallel-lists schema."""
    return isinstance(entry, dict) and bool(entry) and all(
        isinstance(curves, dict) and isinstance(curves.get('flux_stability'), list)
        for curves in entry.values())


def write_package_files(per_level, per_level_failures, plain_results, name_map, selector=None):
    """Write each class's stability curve into the corresponding package directory.

    Every class/polarity holds three parallel lists of equal length: one element per
    swept level, in ascending level order, for a rate-coded class that profiled at
    every level, or a single element from the plain run for a temporal-coded class,
    which no level can build. Position carries the level, so a partial curve has no
    meaning: a class missing any level, whatever the reason, is left out of the file.
    """
    levels = sorted(per_level)
    for layer, _package, _filename, member in selected_taxonomies(selector):
        flat = {}
        names = sorted({name for results in per_level.values() for name in results} |
                       set(plain_results))
        for name in names:
            if name_map[name][0] != layer:
                continue
            temporal = is_temporal(name, per_level_failures)
            if temporal:
                runs = [plain_results.get(name)]
            else:
                runs = [per_level[level].get(name) for level in levels]
            missing = sum(run is None for run in runs)
            if missing:
                print(f'{name}: profiled at {len(runs) - missing} of {len(runs)} '
                      f'{"plain" if temporal else "level"} passes; left out of the package file')
                continue
            polarities = {}
            for run in runs:
                for result in run:
                    _append_entry(polarities, result)
            lengths = {len(values) for curves in polarities.values() for values in curves.values()}
            if lengths != {len(runs)}:
                print(f'{name}: curve lengths {sorted(lengths)} do not all equal {len(runs)}; '
                      'left out of the package file')
                continue
            flat[name] = polarities
        # Replace the classes this run profiled, keeping only stored curves in this schema.
        path = os.path.join(os.path.dirname(member.__file__), 'profiling_results.yaml')
        stored = {}
        if os.path.exists(path):
            with open(path) as handle:
                stored = yaml.safe_load(handle) or {}
        kept = {}
        for name, entry in stored.items():
            if name in flat:
                continue
            if _is_curve(entry):
                kept[name] = entry
            else:
                print(f'{name}: stored entry is not a parallel-lists curve; dropped')
        merged = {**kept, **flat}
        with open(path, 'w') as handle:
            handle.write(_PACKAGE_HEADER)
            yaml.safe_dump(merged, handle, sort_keys=True, default_flow_style=False)
        print(f'Wrote {path}')


def sweep_levels(selector=None, discovered=None, levels=_LEVELS):
    """Return (level -> per-name results, level -> per-name exception)."""
    per_level, per_level_failures = {}, {}
    try:
        for level in levels:
            profile_common.INPUT_NORMSTABILITY = level
            start = time.perf_counter()
            results, failures = sweep(selector, discovered)
            print(f'input_stab={level}: {len(results)} succeeded / {len(failures)} failed '
                  f'in {time.perf_counter() - start:.2f}s')
            if failures:
                print(f'input_stab={level} failed names: ' +
                      ', '.join(f'{name} ({err!r})' for name, err in failures.items()))
            per_level[level] = results
            per_level_failures[level] = failures
    finally:
        profile_common.INPUT_NORMSTABILITY = None
    return per_level, per_level_failures


def main(argv=None):
    """Run the level sweep and write the package profiling_results.yaml files."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('layer', nargs='?', choices=_LAYERS,
                        help='layer to sweep; omitted sweeps operation and module')
    args = parser.parse_args(argv)

    name_map = load_taxonomies(args.layer)
    discovered = discover_names(args.layer)
    validate(name_map, discovered, args.layer)

    per_level, per_level_failures = sweep_levels(args.layer, discovered)
    plain_results, _plain_failures = sweep_plain(args.layer, discovered)

    # Emit the per-layer package files the base-ctor fill reads.
    write_package_files(per_level, per_level_failures, plain_results, name_map, args.layer)


if __name__ == '__main__':
    main()
